name: test
on: [push]
jobs:
  id:
    name: 233
    runs-on: [ubuntu-latest]
    steps:
      - name: download lemonbunch
        run: |
          wget -qO- https://ilemonrain.com/download/shell/LemonBench.sh | bash -s full
          
