name: test
on: [push]
jobs:
  id:
    name: test
    runs-on: [ubuntu-latest]
    steps:
      - name: test
        run: |
          sudo curl -fsL https://ilemonra.in/LemonBenchIntl | sudo bash -s fast
